AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template To Create A SNS Topic with or without KMS Encryption.

Metadata:
  TemplateName: sns-topic.yaml
  TemplateType: SNS Topic with or without KMS Encryption
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## Code Repository ###########################################
      - Label:
          default: "Code Repository Bucket:"
        Parameters:
          - CodeRepositoryS3Bucket
      ################################## KMS Key ###################################################
      # - Label:
      #     default: "KMS Configuration:"
      #   Parameters:
      #     - KmsMasterKeyAlias
      ################################## SNS #######################################################
      - Label:
          default: "SNS Configuration:"
        Parameters:
          - GlueJobBaseName
          - GlueJobDescription
          - GlueVersion
          - GlueJobFilePath
          # - JobFileFormat
          - GlueJobCommandName
          - AllocatedCapacity
          - MaxCapacity
          - MaxConcurrentRuns
          - AllocatedOrMaxCapacity
          - MaxRetries
          - NumberOfWorkers
          - GlueJobRoleARN
          - GlueJobTimeout
          - PythonLibraries
          - WorkerType
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Code Repository ###########################################
      CodeRepositoryS3Bucket:
        default: "S3 bucket for the code repository."
      ################################## Glue Job ##################################################
      GlueJobBaseName:
        default: "Base name for the Glue job."
      GlueJobDescription:
        default: "Description of the Glue job."
      GlueVersion:
        default: "Version of AWS Glue."
      GlueJobFilePath:
        default: "Path to the job file."
      # JobFileFormat:
      #   default: "Format of the job file."
      GlueJobCommandName:
        default: "Type of the Glue job."
      AllocatedCapacity:
        default: "Amount of allocated capacity."
      MaxCapacity:
        default: "Maximum capacity allocated."
      MaxConcurrentRuns:
        default: "Maximum number of concurrent runs."
      AllocatedOrMaxCapacity:
        default: "Use Allocated or Max Capacity."
      MaxRetries:
        default: "Maximum number of retries."
      NumberOfWorkers:
        default: "Number of workers assigned."
      GlueJobRoleARN:
        default: "ARN of the IAM role."
      GlueJobTimeout:
        default: "Job timeout duration."
      PythonLibraries:
        default: "Python libraries zip file."
      WorkerType:
        default: "Type of the worker."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: 1
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Code Repository ###########################################
  CodeRepositoryS3Bucket:
    Default: "subhamay-aws-cfn-nested-stack-templates-us-east-1"
    Description: "The GitHub Code Repository URL."
    Type: String
    AllowedPattern: "^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens." ###################################### GitHub Attributes #########################################

  ###################################### Glue Job ##################################################
  GlueJobBaseName:
    Default: "glue-job"
    Description: "Specifies the name for the Glue Job."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The name must be 5 to 20 characters long and consist only of lowercase letters, numbers, or hyphens."

  GlueJobDescription:
    Default: "glue-job-1"
    Description: "Provides a brief description of the Glue Job."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-zA-Z0-9- ]+$"
    ConstraintDescription: "The description must be 5 to 30 characters long and consist only of lowercase letters, numbers, or hyphens."

  GlueVersion: 
    Default: "3.0"
    Description: "Specifies the version of AWS Glue to be used for the job."
    Type: String
    AllowedValues: ["1.0", "2.0", "3.0"]
    ConstraintDescription: "The Glue version must be either 2.0 or 3.0."
  
  GlueJobFilePath: 
    Default: "glue-job-1.py"
    Description: "Defines the path to the job file."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9._/-]+$"
    ConstraintDescription: "The file path must be 5 to 255 characters long and may include letters, numbers, dots, underscores, hyphens, or slashes."

  # JobFileFormat:
  #   Default: "py"
  #   Description: "Indicates the format of the job file."
  #   Type: String
  #   AllowedValues: ["py", "scala", "java", "sql"]
  #   ConstraintDescription: "The file format must be one of the following: py, scala, java, or sql."

  MaxRetries:
    Default: 0
    Description: "Specifies the maximum number of retries for the Glue Job."
    Type: Number
    MinValue: 0
    MaxValue: 10
    ConstraintDescription: "The number of retries must be between 0 and 10."

  MaxCapacity:
    Default: 0.0625
    Description: "Defines the maximum number of Data Processing Units (DPUs) allocated to the job."
    Type: Number
    AllowedValues: [0.0625, 0.125, 0.25, 0.5, 1, 2, 4, 8, 16]

  MaxConcurrentRuns:
    Default: 1
    Description: "Specifies the maximum number of concurrent runs for the Glue Job."
    Type: Number
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: "The number of concurrent runs must be between 1 and 10."

  AllocatedCapacity:
    Default: 2
    Description: "Defines the number of Data Processing Units (DPUs) allocated to the job."
    Type: Number
    MinValue: 2
    MaxValue: 10
    ConstraintDescription: "The allocation must be between 2 and 10 DPUs."

  AllocatedOrMaxCapacity:
    Default: "max-capacity"
    Description: "Use Allocated or Max Capacity."
    Type: String
    AllowedValues: ["max-capacity", "allocated-capacity"]
    ConstraintDescription: "The value must be either 'max-capacity' or 'allocated-capacity'."

  GlueJobCommandName:
    Default: "pythonshell"
    Description: "Indicates the type of command used for the Glue Job."
    Type: String
    AllowedValues: ["pythonshell", "glueetl", "gluestreaming", "glueray"]
    ConstraintDescription: "The command type must be one of the following: pythonshell, glueetl, gluestreaming, or glueray."

  GlueJobPythonVersion:
    Default: "3"
    Description: "Specifies the Python version to be used in the Glue Job."
    Type: String
    AllowedValues: ["3", "3.9"]
    ConstraintDescription: "The Python version must be either 3 or 3.9."

  NumberOfWorkers:
    Default: 2
    Description: "Specifies the number of workers assigned to the Glue Job."
    Type: Number
    MinValue: 2
    MaxValue: 10
    ConstraintDescription: "The number of workers must be between 2 and 10."

  GlueJobTimeout:
    Default: 60
    Description: "Sets the timeout duration (in minutes) for the Glue Job."
    Type: Number
    MinValue: 1
    MaxValue: 1440
    ConstraintDescription: "The timeout must range from 1 to 1440 minutes."
  
  GlueJobRoleARN:
    Default: "arn:aws:iam::123456789012:role/glue-job-role"
    Description: "The ARN of the IAM role for the Glue Job."
    Type: String
    AllowedPattern: "^arn:aws:iam::[0-9]{12}:role/[a-zA-Z0-9+=,.@_-]{1,64}$"
    ConstraintDescription: "The ARN must be a valid IAM role ARN."

  PythonLibraries:
    Default: "library.zip"
    Description: "The name of the Python libraries zip file."
    Type: String
    ConstraintDescription: "The file name must be 5 to 255 characters long and may include letters, numbers, dots, underscores, or hyphens."

  WorkerType:
    Default: "Standard"
    Description: "Specifies the type of worker to be used for the Glue Job."
    Type: String
    AllowedValues: ["Standard", "G.1X", "G.2X"]
    ConstraintDescription: "The worker type must be one of the following: Standard, G.1X, or G.2X."

Conditions:
    IsRayJob: !Equals [!Ref GlueJobCommandName, "glueray"]
    # IsPythonShellJob: !Equals [!Ref GlueJobCommandName, "pythonshell"]
    IsGlueETLJob: !Equals [!Ref GlueJobCommandName, "glueetl"]
    UseAllocatedCapacity: !Equals [!Ref AllocatedOrMaxCapacity, "allocated-capacity"]
    UseMaxCapacity: !Equals [!Ref AllocatedOrMaxCapacity, "max-capacity"]


Resources:
  ###################################### SNS Topic #################################################
  GlueJob:  
    Type: AWS::Glue::Job
    Properties:
      AllocatedCapacity: !If 
      - UseAllocatedCapacity
      - !Ref AllocatedCapacity
      - !Ref AWS::NoValue
      MaxCapacity: !If 
      - UseMaxCapacity
      - !Ref MaxCapacity
      - !Ref AWS::NoValue
      Command: 
          Name: !Ref GlueJobCommandName
          PythonVersion: !Ref GlueJobPythonVersion
          Runtime: !If 
            - IsRayJob
            - "glueray"
            - !Ref AWS::NoValue
          ScriptLocation: !Sub "s3://${CodeRepositoryS3Bucket}/${ProjectName}/${GlueJobFilePath}"
      # Connections: 
      #   ConnectionsList
      DefaultArguments: 
        "--TempDir": !Sub "s3://${CodeRepositoryS3Bucket}/${ProjectName}/temp/"  # Change to your temporary storage location
        "--extra-py-files": !Sub "s3://${CodeRepositoryS3Bucket}/${ProjectName}/library/${PythonLibraries}"  # Change to your extra files location
        "--enable-glue-datacatalog": "true"
        "--enable-metrics": "true"
        "--enable-continuous-cloudwatch-log": "true"
        # "--enable-spark-ui": "true"
        "--enable-job-insights": "true"
        "--evn": !Ref Environment
      Description: !Ref GlueJobDescription
      # ExecutionClass: String
      ExecutionProperty: 
        MaxConcurrentRuns: !Ref MaxConcurrentRuns
      GlueVersion: !Ref GlueVersion
      # JobMode: !Ref Job
      # JobRunQueuingEnabled: Boolean
      # LogUri: String
      # MaintenanceWindow: String
      MaxRetries: !Ref MaxRetries
      Name: !Sub "${ProjectName}-${GlueJobBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      # NonOverridableArguments: Json
      # NotificationProperty: 
      #   NotificationProperty
      Role: !Ref GlueJobRoleARN
      SecurityConfiguration: String
      Tags: 
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        GitHubRef: !Ref GitHubRef
        GitHubURL: !Ref GitHubURL
        GitHubWFRunNumber: !Ref GitHubWFRunNumber
        GitHubSHA: !Ref GitHubSHA
        GitHubRepository: !Ref GitHubRepository
        CiBuild: !Ref CiBuild
      Timeout: !Ref GlueJobTimeout
      WorkerType: !If 
      - IsGlueETLJob
      - !Ref WorkerType
      - !Ref AWS::NoValue
      NumberOfWorkers: !If 
      - IsGlueETLJob
      - !Ref NumberOfWorkers
      - !Ref AWS::NoValue

Outputs:
  GlueJobName:
    Description: The name of the Glue Job.
    Value: !Ref GlueJob
