AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template To Create A SNS Topic with or without KMS Encryption.

Metadata:
  TemplateName: glue-crawler.yaml
  TemplateType: Glue Crawler Configuration
  Description: This CloudFormation template defines the creation of an AWS Glue Crawler with configurable parameters.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Jan 11, 2025 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    GlueDatabaseName: The base name of the Glue Database. Must be between 6 and 40 characters, starting with a letter and containing lowercase letters, numbers, and dashes.
    GlueCrawlerBaseName: The base name of the Glue Crawler. Must be between 6 and 40 characters, starting with a letter and containing lowercase letters, numbers, and dashes.
    GlueCrawlerDescription: The description of the Glue Crawler. Can contain alphanumeric characters, spaces, dots, dashes, and underscores.
    GlueCrawlerRole: The base name of the Glue IAM role. Must be between 5 and 30 characters, containing alphanumeric characters and dashes.
    GlueCrawlerTablePrefixName: The prefix name for Glue tables. Must be between 5 and 30 characters, containing alphanumeric characters, dashes, and underscores.
    GlueClassifiers: Custom-defined classifiers used by Glue. Must be a comma-separated list of valid classifier names, containing only alphanumeric characters, dashes, or underscores.
    GlueDataBucketName: The base name of the Glue Data Bucket. Must be between 3 and 63 characters, containing lowercase letters, numbers, dots, and hyphens.
    GlueDataFolder1: The base name of the first Glue Data Folder. Must be between 5 and 20 characters, containing lowercase letters, numbers, dots, and hyphens.
    GlueDataFolder2: The base name of the second Glue Data Folder. Must be between 3 and 63 characters, containing lowercase letters, numbers, dots, and hyphens.
    GlueDataFolder3: The base name of the third Glue Data Folder. Must be between 3 and 63 characters, containing lowercase letters, numbers, dots, and hyphens.

  Conditions:
    GlueDataFolder2: Checks if GlueDataFolder2 is not an empty string.
    GlueDataFolder3: Checks if GlueDataFolder3 is not an empty string.

  Resources:
    GlueCrawler: An AWS Glue Crawler resource with properties such as name, role, description, database name, S3 targets, table prefix, schema change policy, configuration, and tags.

  Outputs:
    GlueCrawlerArn: The ARN of the Glue Crawler.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## Glue Crawler ##############################################
      - Label:
          default: "Glue Crawler Configuration:"
        Parameters:
          - GlueDatabaseName
          - GlueCrawlerBaseName
          - GlueCrawlerDescription
          - GlueCrawlerRole
          - GlueCrawlerTablePrefixName
          - GlueClassifiers
      ################################## S3 Bucket #################################################
      - Label:
          default: "S3 Bucket Configuration:"
        Parameters:
          - GlueDataBucketName
          - GlueDataFolder1
          - GlueDataFolder2
          - GlueDataFolder3
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Glue Crawler #############################################
      GlueDatabaseName:
        default: "The base name assigned to the Glue database."
      GlueCrawlerBaseName:
        default: "The base name assigned to the Glue crawler."
      GlueCrawlerDescription:
        default: "A brief description of the Glue crawler."
      GlueCrawlerRole:
        default: "The IAM role associated with the Glue crawler."
      GlueCrawlerTablePrefixName:
        default: "The prefix used for naming Glue crawler tables."
      GlueClassifiers:
        default: "Custom-defined classifiers used by Glue."
      ################################## S3 Bucket #############################################
      GlueDataBucketName:
        default: "The name of the S3 bucket storing Glue data."
      GlueDataFolder1:
        default: "The first folder within the Glue data S3 bucket."
      GlueDataFolder2:
        default: "The second folder within the Glue data S3 bucket."
      GlueDataFolder3:
        default: "The third folder within the Glue data S3 bucket."


Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."
  GitHubRepository:

    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Glue Crawler ##############################################
  GlueDatabaseName:
    Default: "glue-db"
    Description: "The base name of the Glue Database. The database name will be created with the environment and region as suffix."
    Type: String
    MinLength: "6"
    MaxLength: "40"
    AllowedPattern: "^[a-z][a-z0-9-]*$"
    ConstraintDescription: "The length of Glue Database base name should be between 8 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."

  GlueCrawlerBaseName:
    Default: "glue-db"
    Description: "The base name of the Glue Crawler. The crawler name will be created by appending the environment and region."
    Type: String
    MinLength: "6"
    MaxLength: "40"
    AllowedPattern: "^[a-z][a-z0-9-]*$"
    ConstraintDescription: "The length of Glue Database base name should be between 8 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."

  GlueCrawlerDescription:
    Default: ""
    Description: "Glue Database Description"
    Type: String
    AllowedPattern: "^$|^[a-zA-Z0-9-. _]*$"
    ConstraintDescription: "The length should be between 30 and 100, must alphanumeric character, space, dot dash or underscore."

  GlueCrawlerRole:
    Default: crawler-role
    Description: "The base name of the glue IAM role."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-zA-Z0-9-]*$"
    ConstraintDescription: "The length should be between 5 and 30, and can only contain alphanumeric characters and dashes."

  GlueCrawlerTablePrefixName:
    Default: glue-table-prefix
    Description: "Glue table prefix."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "[a-zA-Z-_]*"
    ConstraintDescription: "The length should be between 5 and 30, must alphanumeric character, dash (-) or underscore(_)."

  GlueClassifiers:
    Default: ""
    Description: "The base name of the Glue Classifier."
    Type: CommaDelimitedList
    AllowedPattern: "^$|^[a-zA-Z0-9-_]+(,[a-zA-Z0-9-_]+)*$"
    ConstraintDescription: "The Glue Classifiers must be a comma-separated list of valid classifier names, containing only alphanumeric characters, dashes (-), or underscores (_)."

  ###################################### S3 Bucket #################################################
  GlueDataBucketName:
    Default: "glue-data-bucket"
    Description: "The base name of the Glue Data Bucket."
    Type: String
    MinLength: "3"
    MaxLength: "63"
    AllowedPattern: "^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens."

  GlueDataFolder1:
    Default: "glue-data-folder-1"
    Description: "The base name of the Glue Data Folder 1."
    Type: String
    MinLength: "5"
    MaxLength: "20"
    AllowedPattern: "^$|^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens."

  GlueDataFolder2:
    Default: ""
    Description: "The base name of the Glue Data Folder 1."
    Type: String
    AllowedPattern: "^$|^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens."

  GlueDataFolder3:
    Default: ""
    Description: "The base name of the Glue Data Folder 1."
    Type: String
    AllowedPattern: "^$|^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens."

Conditions:
  EnableGlueDataFolder2: !Not [!Equals [!Ref GlueDataFolder2, ""]]
  EnableGlueDataFolder3: !Not [!Equals [!Ref GlueDataFolder3, ""]]
  EnableGlueClassifierConfig: !Not [!Equals [!Join [",", !Ref GlueClassifiers], ""]]

Resources:
  ###################################### Glue Crawler ##############################################
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${ProjectName}-${GlueCrawlerBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      Role: !Ref GlueCrawlerRole 
      Classifiers: !If 
        - EnableGlueClassifierConfig
        - !Ref GlueClassifiers
        - !Ref AWS::NoValue
      Description: !Ref GlueCrawlerDescription
      #Schedule: none, use default run-on-demand
      DatabaseName: !Ref GlueDatabaseName
      Targets:
        S3Targets:
          # S3 Data Sources Path
          - Path: !Sub "s3://${GlueDataBucketName}/${GlueDataFolder1}"
          - Path: !If 
            - EnableGlueDataFolder2
            - !Sub "s3://${GlueDataBucketName}/${GlueDataFolder2}"
            - !Ref AWS::NoValue
          - Path: !If 
            - EnableGlueDataFolder3
            - !Sub "s3://${GlueDataBucketName}/${GlueDataFolder3}"
            - !Ref AWS::NoValue
      TablePrefix: !Ref GlueCrawlerTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
      Tags:
        "ProjectName": !Ref ProjectName
        "Environment": !Ref Environment
        "GitHubRef": !Ref GitHubRef
        "GitHubURL": !Ref GitHubURL
        "GitHubWFRunNumber": !Ref GitHubWFRunNumber
        "GitHubSHA": !Ref GitHubSHA
        "GitHubRepository": !Ref GitHubRepository
        "CiBuild": !Ref CiBuild
Outputs:
  GlueCrawlerArn:
    Description: The Arn Of The Glue Crawler.
    Value: !Ref GlueCrawler