AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Glue Job Trigger.

Metadata:
  TemplateName: glue-trigger.yaml
  TemplateType: Glue Trigger
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## Code Repository ###########################################
      - Label:
          default: "Code Repository Bucket:"
        Parameters:
          - CodeRepositoryS3Bucket
      ################################## KMS Key ###################################################
      # - Label:
      #     default: "KMS Configuration:"
      #   Parameters:
      #     - KmsMasterKeyAlias
      ################################## Glue Trigger ##############################################
      - Label:
          default: "Glue Trigger Configuration:"
        Parameters:
          - GlueTriggerBaseName
          - GlueTriggerDescription
          - GlueTriggerType
          - StartOnCreation
          - GlueTriggerSchedule
          - GlueJobSecurityConfiguration
          - GlueJobName
          - GlueJobTimeout
          - JobBookmarkOption
          - TempDir
          - EnableMetrics
          - ExtraPythonFiles
          - ExtraJars
          - EnableCloudWatchLog
          - EnableS3ParquetOptimizeCommitter
          - DatalakeFormats
          - EnableContinuousLogging
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Code Repository ###########################################
      CodeRepositoryS3Bucket:
        default: "S3 bucket for the code repository."
      ################################## Glue Job Trigger ##########################################
      GlueTriggerBaseName:
        default: "Base name for the Glue job trigger."
      GlueTriggerDescription:
        default: "Description of the Glue trigger."
      GlueTriggerType:
        default: "The type of Glue trigger."
      GlueJobSecurityConfiguration:
        default: "Security configuration for the Glue job."
      GlueJobName:
        default: "Name of the Glue job."
      GlueJobTimeout:
        default: "Timeout duration for the Glue job."
      JobBookmarkOption: 
        default: "The bookmark option for the Glue job."
      EnableMetrics: 
        default: "Enable metrics for the Glue job."
      ExtraPythonFiles: 
        default: "Extra Python files for the Glue job."
      ExtraJars: 
        default: "Extra Jars for the Glue job."
      EnableCloudWatchLog: 
        default: "Enable continuous CloudWatch log for the Glue job."
      EnableS3ParquetOptimizeCommitter: 
        default: "Enable S3 Parquet optimized committer for the Glue job."
      DatalakeFormats: 
        default: "Data lake formats for the Glue job."


Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: 1
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Code Repository ###########################################
  CodeRepositoryS3Bucket:
    Default: "subhamay-aws-cfn-nested-stack-templates-us-east-1"
    Description: "The GitHub Code Repository URL."
    Type: String
    AllowedPattern: "^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens." ###################################### GitHub Attributes #########################################

  ###################################### Glue Job Trigger ##########################################
  GlueTriggerBaseName:
    Default: "glue-trigger"
    Description: "Specifies the name for the Glue Job."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The name must be 5 to 20 characters long and consist only of lowercase letters, numbers, or hyphens."

  GlueTriggerDescription:
      Default: ""
      Description: "A brief description of the Glue Trigger."
      Type: String
      AllowedPattern: "^$|^[a-zA-Z0-9- ]+$"
      ConstraintDescription: "The description must be 5 to 30 characters long and consist only of alphanumeric characters, spaces, hyphens, or underscores."

  GlueTriggerType:
      Default: "ON_DEMAND"
      Description: "Specifies the type of trigger."
      Type: String
      AllowedValues: ["ON_DEMAND", "CONDITIONAL", "SCHEDULED"]
      ConstraintDescription: "The trigger type must be either ON_DEMAND, CONDITIONAL, or SCHEDULED."

  StartOnCreation:
    Default: "false"
    Description: "Specifies whether the trigger should start on creation."
    AllowedValues: ["false", "true"]
    Type: String

  GlueTriggerSchedule:
    Default: "cron(0 0 * * ? *)"
    Description: "Specifies the schedule for the Glue Trigger."
    Type: String

  GlueJobSecurityConfiguration:
    Default: ""
    Description: "The name of the security configuration to be used."
    Type: String
    AllowedPattern: "^$|^[a-zA-Z0-9-]+$"
    ConstraintDescription: "The name must be 5 to 20 characters long and consist only of alphanumeric characters or hyphens."

  GlueJobName:
    Default: "glue-job"
    Description: "Specifies the name for the Glue Job."
    Type: String
    MinLength: 5
    MaxLength: 100
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The name must be 5 to 10 characters long and consist only of lowercase letters, numbers, or hyphens."

  GlueJobTimeout:
    Default: 2880
    Description: "Specifies the timeout duration for the Glue Job."
    Type: Number
    MinValue: 30
    MaxValue: 2880
    ConstraintDescription: "The timeout duration must be between 30 and 2880 minutes."

  JobBookmarkOption:
    Default: "job-bookmark-disable"
    Description: "Specifies the bookmark option for the Glue Job."
    Type: String
    AllowedValues: ["job-bookmark-disable", "job-bookmark-enable"]
    ConstraintDescription: "The bookmark option must be either job-bookmark-disable or job-bookmark-enable."

  TempDir:  
    Default: "s3://my-bucket/temp/"
    Description: "Specifies the temporary directory for the Glue Job."
    Type: String
    AllowedPattern: "^$|^s3://[a-z0-9.-]+/.*$"
    ConstraintDescription: "The temporary directory must be an S3 path."

  EnableMetrics: 
    Default: "true"
    Description: "Specifies whether to enable metrics for the Glue Job."
    Type: String
    AllowedValues: ["true", "false"]
    ConstraintDescription: "The value must be either true or false."

  ExtraPythonFiles:
    Default: "s3://my-bucket/scripts/mylibrary.zip"
    Description: "Specifies the extra Python files for the Glue Job."
    Type: String
    AllowedPattern: "^s3://[a-z0-9.-]+/.*$"
    ConstraintDescription: "The extra Python files must be an S3 path."

  ExtraJars:
    Default: "s3://my-bucket/jars/myjar.jar"
    Description: "Specifies the extra Jars for the Glue Job."
    Type: String
    AllowedPattern: "^$|^s3://[a-z0-9.-]+/.*$"
    ConstraintDescription: "The extra Jars must be an S3 path."

  EnableCloudWatchLog:
    Default: "true"
    Description: "Specifies whether to enable continuous CloudWatch log for the Glue Job."
    Type: String
    AllowedValues: ["true", "false"]
    ConstraintDescription: "The value must be either true or false."

  EnableS3ParquetOptimizeCommitter:
    Default: "true"
    Description: "Specifies whether to enable S3 Parquet optimized committer for the Glue Job."
    Type: String
    AllowedValues: ["true", "false"]
    ConstraintDescription: "The value must be either true or false."

  DatalakeFormats:
    Default: "iceberg,hudi,delta"
    Description: "Specifies the data lake formats for the Glue Job."
    Type: String
    AllowedValues: ["iceberg,hudi,delta", "hudi,delta", "hudi,iceberg,delta", "delta"]
    ConstraintDescription: "The value must be either 'iceberg,hudi,delta', 'hudi,delta', 'hudi,iceberg,delta', or 'delta'."

Conditions:
    IsScheduledTrigger: !Equals [!Ref GlueTriggerType, "SCHEDULED"]
    IsPythonFilesS3Reference: !Not [!Equals [!Ref ExtraPythonFiles, ""]]
    IsExtraJarsS3Reference: !Not [!Equals [!Ref ExtraJars, ""]]

Resources:
  ###################################### Glue Trigger ##############################################
  GlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: !Sub "${ProjectName}-${GlueTriggerBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      Description: !Ref GlueTriggerDescription
      WorkflowName: !Ref GlueJobName
      Type: !Ref GlueTriggerType
      Actions:
      - JobName: !Ref GlueJobName
        SecurityConfiguration: !Ref GlueJobSecurityConfiguration
        Timeout: !Ref GlueJobTimeout
        Arguments:
          --job-bookmark-option: !Ref JobBookmarkOption
          --custom-arg: 'value'
          --TempDir: !Ref TempDir #s3://my-bucket/temp/'
          --enable-metrics: !Ref EnableMetrics #true'
          --extra-py-files: !If 
            - IsPythonFilesS3Reference
            - !Ref ExtraPythonFiles #'s3://my-bucket/scripts/mylibrary.zip'
            - !Ref 'AWS::NoValue'
          --extra-jars: !If 
            - IsExtraJarsS3Reference
            - !Ref ExtraJars ##'s3://my-bucket/jars/myjar.jar'
            - !Ref 'AWS::NoValue'
          --enable-continuous-cloudwatch-log: !Ref EnableCloudWatchLog ##'true'
          --enable-s3-parquet-optimized-committer: !Ref EnableS3ParquetOptimizeCommitter ## 'true'
          --datalake-formats: !Ref DatalakeFormats ##'iceberg,hudi,delta'
      StartOnCreation: !Ref StartOnCreation
      Schedule: !If 
      - IsScheduledTrigger
      - !Ref GlueTriggerSchedule
      - !Ref 'AWS::NoValue'
      Tags:
        - Key: "ProjectName"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: !Ref Environment
        - Key: "GitHubRef"
          Value: !Ref GitHubRef
        - Key: "GitHubURL"
          Value: !Ref GitHubURL
        - Key: "GitHubWFRunNumber"
          Value: !Ref GitHubWFRunNumber
        - Key: "GitHubSHA"
          Value: !Ref GitHubSHA
        - Key: "GitHubRepository"
          Value: !Ref GitHubRepository
        - Key: "CiBuild"
          Value: !Ref CiBuild

Outputs:
  GlueTriggerName:
    Description: The name of the Glue Trigger.
    Value: !Ref GlueTrigger
