AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Glue Job Trigger.

Metadata:
  TemplateName: glue-trigger.yaml
  TemplateType: Glue Trigger
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - CiBuild
      ################################## KMS Key ###################################################
      - Label:
          default: "KMS Configuration:"
        Parameters:
          - KmsMasterKeyAlias
      ################################## Glue Security Configuration ###############################
      - Label:
          default: "Glue Security Configuration:"
        Parameters:
          - SecurityConfigurationName
          - CloudWatchEncryptionMode
          - JobBookmarksEncryptionMode
          - S3EncryptionMode

    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Glue Security Configuration ###############################
      SecurityConfigurationName:
        default: "The name of the Glue Security Configuration"
      CloudWatchEncryptionMode:
        default: "The CloudWatch encryption mode."
      JobBookmarksEncryptionMode:
        default: "The Job Bookmarks encryption mode."
      S3EncryptionMode:
        default: "The S3 encryption mode."
      
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### KMS Key ###################################################
  KmsMasterKeyAlias:
    Default: "alias/glue-job-1"
    Description: "The KMS master key alias to be used for server-side encryption."
    Type: String
    AllowedPattern: "^alias/[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The KMS master key alias must start with 'alias/' and can only contain alphanumeric characters, underscores, and hyphens."

  ###################################### Glue Security Configuration ###############################
  SecurityConfigurationName:
    Default: "glue-security-configuration-1"
    Description: "The name of the Glue Security Configuration."
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z0-9-]+$"
    ConstraintDescription: "The Glue Security Configuration name must be composed of only alphanumeric characters and dashes."  

  CloudWatchEncryptionMode:
    Default: "DISABLED"
    Description: "The CloudWatch encryption mode."
    Type: String
    AllowedValues: ["DISABLED", "SSE-KMS"]
    ConstraintDescription: "The CloudWatch encryption mode must be either DISABLED or SSE-KMS."

  JobBookmarksEncryptionMode:
    Default: "DISABLED"
    Description: "The Job Bookmarks encryption mode."
    Type: String
    AllowedValues: ["DISABLED", "CSE-KMS"]
    ConstraintDescription: "The Job Bookmarks encryption mode must be either DISABLED or SSE-KMS."

  S3EncryptionMode:
    Default: "DISABLED"
    Description: "The S3 encryption mode."
    Type: String
    AllowedValues: ["DISABLED", "SSE-KMS"]
    ConstraintDescription: "The S3 encryption mode must be either DISABLED or SSE-KMS."

Conditions:
    CloudWatchEncryptionEnabled: !Not [!Equals [!Ref CloudWatchEncryptionMode, "DISABLED"]]
    JobBookmarksEncryptionEnabled: !Not [!Equals [!Ref JobBookmarksEncryptionMode, "DISABLED"]]
    S3EncryptionEnabled: !Not [!Equals [!Ref S3EncryptionMode, "DISABLED"]] 

Resources:
  ###################################### Glue Trigger ##############################################
  GlueSecurityConfiguration:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration: 
        CloudWatchEncryption: 
          CloudWatchEncryptionMode: !Ref CloudWatchEncryptionMode
          KmsKeyArn: !If 
          - CloudWatchEncryptionEnabled
          - !Ref KmsMasterKeyAlias
          - !Ref "AWS::NoValue"
        JobBookmarksEncryption: 
          JobBookmarksEncryptionMode: !Ref JobBookmarksEncryptionMode
          KmsKeyArn: !If 
          - JobBookmarksEncryptionEnabled
          - !Ref KmsMasterKeyAlias
          - !Ref "AWS::NoValue"
        S3Encryptions: 
          - KmsKeyArn: !If 
            - S3EncryptionEnabled
            - !Ref KmsMasterKeyAlias
            - !Ref "AWS::NoValue"
            S3EncryptionMode: !Ref S3EncryptionMode
      Name: !Sub "${ProjectName}-${SecurityConfigurationName}-${Environment}-${CiBuild}" 

Outputs:
  GlueTriggerName:
    Description: The name of the Glue Trigger.
    Value: !Ref GlueSecurityConfiguration
