AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create AWS Glue Database.

Metadata:
  TemplateName: glue-database.yaml
  TemplateType: Glue Database Configuration
  TemplateVersion: 1.0.0
  Description: This CloudFormation template defines the creation of an AWS Glue Database with configurable parameters.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Jan 11, 2025-- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The name of the project to be used as a resource tag value. It must be between 5 and 30 characters long and can only contain lowercase alphabets, numbers, or dashes.
    Environment: The environment name to be used as a resource tag value. It must be one of the following values - "devl", "test", or "prod".
    CiBuild: The CI build identifier of the feature branch to be appended to the resource name.
    GlueDatabaseBaseName: The base name of the Glue Database. It must be between 6 and 40 characters long and can only contain lowercase letters, numbers, or dashes, and must start with a letter.
    GlueDatabaseDescription: The description of the Glue Database. It can contain alphanumeric characters, spaces, dots, dashes, or underscores.

  Resources:
    GlueDatabase: An AWS Glue Database resource with a name constructed from the ProjectName, GlueDatabaseBaseName, Environment, AWS Region, and CiBuild parameters. The description is set from the GlueDatabaseDescription parameter.

  Outputs:
    GlueDatabaseId: The ID of the created Glue Database.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - CiBuild
      ################################## Glue Database #############################################
      - Label:
          default: "Glue Database Configuration:"
        Parameters:
          - GlueDatabaseBaseName
          - GlueDatabaseBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Glue Database #############################################
      GlueDatabaseBaseName:
        default: "Base name for the Glue database."
      GlueDatabaseDescription:
        default: "Description of the Glue database."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Glue Database #############################################
  GlueDatabaseBaseName:
    Default: "glue-db"
    Description: "The base name of the Glue Database. The database name will be created by appending the environment and region."
    Type: String
    MinLength: "6"
    MaxLength: "40"
    AllowedPattern: "^[a-z][a-z0-9-]*$"
    ConstraintDescription: "The length of Glue Database base name should be between 8 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
    
  GlueDatabaseDescription:
    Default: ""
    Description: "Glue Database Description"
    Type: String
    AllowedPattern: "^$|^[a-zA-Z0-9-. _]*$"
    ConstraintDescription: "The length should be between 30 and 100, must alphanumeric character, space, dot dash or underscore."

Resources:
  ###################################### Glue Database #############################################
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "${ProjectName}-${GlueDatabaseBaseName}-${Environment}-${AWS::Region}${CiBuild}"
        Description: !Ref GlueDatabaseDescription
      CatalogId: !Ref AWS::AccountId

Outputs:
  GlueDatabaseId:
    Description: Glue database Id
    Value: !Ref GlueDatabase
