AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create an EC2 Instance.

Metadata:
  TemplateName: ec2-instance.yaml
  TemplateType: EC2 Instance
  Description: >
    This CloudFormation template defines an EC2 instance with various parameters and properties..
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Jan 15, 2025 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    LatestAmiId: The ID of the latest Amazon Machine Image (AMI). Must be a valid ID starting with 'ami-' followed by 8 to 17 hexadecimal characters.
    EC2InstanceProfile: The ARN of the EC2 instance profile. Must be a valid ARN starting with 'arn:aws:iam::', followed by a 12-digit account number, and 'instance-profile/'.
    EC2InstanceType: The EC2 instance type. Must be one of "t2.micro", "t2.small", "t2.medium", or "t2.large".
    SubnetId: The Subnet ID for the EC2 instance. Must be in the format 'subnet-' followed by either 8 or 17 hexadecimal characters.
    SubnetType: Defines if the EC2 instance will be deployed in a Public or Private Subnet. Must be one of "public" or "private".
    SecurityGroupId: List of Security Group IDs for the Lambda function. Must be a comma-separated list of valid security group IDs.


  Resources:
    EC2Instance: > 
      An EC2 instance with properties such as instance type, image ID, IAM instance profile, subnet ID, 
      and security group IDs. Tags are applied to the instance using the provided parameters.

  Outputs:
    InstanceId: The ID of the instance.
    PrivateDnsName: The private DNS name of the specified instance.
    PrivateIp: The private IP address of the specified instance.
    PublicDnsName: The public DNS name of the specified instance.
    PublicIp: The public IP address of the specified instance.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## SNS #######################################################
      - Label:
          default: "EC2 Configuration:"
        Parameters:
          - LatestAmiId
          - EC2InstanceProfileName
          - EC2InstanceType
          - SubnetId
          - SubnetType
          - SecurityGroupId
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## EC2 Instance ##############################################
      LatestAmiId:
        default: "The identifier for the most recent Amazon Machine Image (AMI)."
      EC2InstanceProfileName:
        default: "The name assigned to the EC2 instance profile."
      EC2InstanceType:
        default: "The designated type for the EC2 instance."
      SubnetId:
        default: "The unique identifier for the subnet."
      SubnetType:
        default: "Specifies whether the subnet is public or private."
      SecurityGroupId:
        default: "A list of security group identifiers."

        
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."
  
  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."
  
  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number
  
  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."
  
  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."
  
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### EC2 Instance ##############################################
  LatestAmiId:
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: "Specifies the latest Amazon Machine Image (AMI) ID."
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    AllowedPattern: "^/aws/service/ami-[a-zA-Z0-9-_/]+$"
    ConstraintDescription: "The AMI ID must follow the pattern '/aws/service/ami-' and include valid characters."

  EC2InstanceProfileName:
    Default: ""
    Description: "Name of the EC2 instance profile."
    Type: String
    MaxLength: "128"
    AllowedPattern: "^$|^[a-zA-Z0-9_-]{1,128}$"
    ConstraintDescription: >
      "The instance profile name must be 1–128 characters long and consist of 
      letters, numbers, underscores (_), or hyphens (-)."

  EC2InstanceType:
    Default: "t2.micro"
    Description: "The instance type for the EC2."
    Type: String
    AllowedValues: ["t2.micro", "t2.small", "t2.medium", "t2.large"]
    ConstraintDescription: "Acceptable instance types are t2.micro, t2.small, t2.medium, or t2.large."

  SubnetId:
    Default: "subnet-1234567890abcdef0"
    Description: "The Subnet ID for launching the EC2 instance."
    Type: String
    AllowedPattern: "^(subnet-)([a-f0-9]{8}|[a-f0-9]{17})$"
    ConstraintDescription: "Subnet IDs must start with 'subnet-' followed by 8 or 17 hexadecimal characters."

  SubnetType:
    Default: "private"
    Description: "Defines if the EC2 instance will be deployed in a Public or Private Subnet."
    Type: String
    AllowedValues: ["public", "private"]
    ConstraintDescription: "Subnet type must be either public or private."

  SecurityGroupId:
    Default: ""
    Description: "Comma-separated list of Security Group IDs associated with the instance."
    Type: String
    AllowedPattern: "^$|^sg-[a-zA-Z0-9]+(,sg-[a-zA-Z0-9]+)*$"
    ConstraintDescription: >
      "Security Group IDs must be valid and, if multiple, separated by commas."

Conditions:
  IsPublicSubnet: !Equals [!Ref SubnetType, "public"]
  HasEc2InstanceProfile: !Not [!Equals [!Ref EC2InstanceProfileName, ""]]
  
Resources:
  ###################################### EC2 Instance ##############################################
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !If 
      - HasEc2InstanceProfile
      - !Ref EC2InstanceProfileName
      - !Ref AWS::NoValue
      SubnetId: !Ref SubnetId
      SecurityGroupIds: 
        - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ec2${CiBuild}"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
Outputs:
  InstanceId:
    Description: The ID of the instance.
    Value: !Ref EC2Instance
  PrivateDnsName:
    Description: The private DNS name of the specified instance. 
    Value: !GetAtt EC2Instance.PrivateDnsName
  PrivateIp:
    Description: The private IP address of the specified instance.
    Value: !GetAtt EC2Instance.PrivateIp
  PublicDnsName:
    Condition: IsPublicSubnet
    Description: The public DNS name of the specified instance.
    Value: !GetAtt EC2Instance.PublicDnsName
  PublicIp:
    Condition: IsPublicSubnet
    Description: The public IP address of the specified instance.
    Value: !GetAtt EC2Instance.PublicIp