AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create EC2 Instance Connect Endpoint.

Metadata:
  TemplateName: ec2-instance-connect.yaml
  TemplateType: VPC with optionally IPV6 CIDR enabled
  Description: >
    This CloudFormation template creates an EC2 Instance Connect Endpoint with specified parameters and tags.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 01, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    SecurityGroupId: Security Group ID. Must be a valid ID starting with 'sg-' followed by 8 to 17 hexadecimal characters.
    SubnetId: Subnet ID. Must be a valid ID starting with 'subnet-' followed by 8 to 17 hexadecimal characters.
    PreserveClientIp: Preserve Client IP. Must be either true or false.

    Resources:
      Ec2InstanceConnectEndpoint: Creates an AWS::EC2::InstanceConnectEndpoint resource with the specified properties and tags.

    Outputs:
      EC2InstanceConnectEndpoint: The EC2 Instance Connect Endpoint ID.
      EC2InstanceConnectId: The EC2 Instance Connect ID.
  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## VPC #######################################################
      - Label:
          default: "EC2 Instance Connect EndpointConfiguration:"
        Parameters:
          - SecurityGroupId
          - SubnetId
          - PreserveClientIp

    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## EC2 Instance Connect ######################################
      SecurityGroupId:
        default: "ID of the security group."
      SubnetId:
        default: "ID of the subnet."
      PreserveClientIp:
        default: "Option to preserve the client IP."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### VPC #######################################################
  SecurityGroupId:
    Default: "sg-1234567890abcdef0"
    Description: "Security Group Id."
    Type: String
    AllowedPattern: "^sg-[a-fA-F0-9]{8,17}$"
    ConstraintDescription: "The Security Group ID must be a valid ID starting with 'sg-' followed by 8 to 17 hexadecimal characters."

  SubnetId:
    Default: "subnet-1234567890abcdef0"
    Description: "Subnet Id."
    Type: String
    AllowedPattern: "^subnet-[a-fA-F0-9]{8,17}$"
    ConstraintDescription: "The Subnet ID must be a valid ID starting with 'subnet-' followed by 8 to 17 hexadecimal characters."

  PreserveClientIp:
    Default: "false"
    Description: "Preserve Client IP."
    Type: String
    AllowedValues:
      - "true"
      - "false"

Resources:
  ###################################### EC2 Instance Connect ######################################
  Ec2InstanceConnect:
    Type: AWS::EC2::InstanceConnectEndpoint
    Properties:
      # ClientToken: String
      PreserveClientIp: !Ref PreserveClientIp
      SecurityGroupIds: 
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-ec2ice${CiBuild}"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
Outputs:
  ###################################### EC2 Instance Connect ######################################
  EC2InstanceConnectEndpoint:
    Description: EC2 Instance Connect Endpoint Id
    Value: !Ref Ec2InstanceConnect
  EC2InstanceConnectId:
    Description: EC2 Instance Connect Id
    Value: !GetAtt Ec2InstanceConnect.Id
