AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a NAT Gateway

Metadata:
  TemplateName: ec2-instance-connect.yaml
  TemplateType: Nat Gateway with EIP
  Description: >
    This CloudFormation template creates a NAT Gateway along with its associated resources.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 14, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    PrivateRouteTableId: The ID of the private route table. Must be a valid security group ID starting with 'sg-' followed by 8 to 17 hexadecimal characters.
    PublicSubnetId: The ID of the public subnet. Must be a valid subnet ID starting with 'subnet-' followed by 8 to 17 hexadecimal characters.

    Resources:
      NatGatewayEIP: An Elastic IP for the NAT Gateway with tags for project name, environment, GitHub repository, reference, URL, workflow run number, and SHA.
      NatGateway: The NAT Gateway resource with tags for project name, environment, GitHub repository, reference, URL, workflow run number, and SHA.
      RouteNATGateway: A route in the private route table that directs traffic to the NAT Gateway.

    Outputs:
      NatGatewayId: The ID of the created NAT Gateway.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      #################################### VPC #######################################################
      - Label:
          default: "NAT Gateway Configuration:"
        Parameters:
          - PrivateRouteTableId
          - PublicSubnetId

    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################# Nat Gateway ################################################
      PrivateRouteTableId:
        default: "ID of the private route table."
      PublicSubnetId:
        default: "ID of the public subnet."


Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### NAT Gateway ###############################################
  PrivateRouteTableId:
    Default: "rtb-1234567890abcdef0"
    Description: "Private Route Table Id."
    Type: String
    AllowedPattern: "^rtb-[a-fA-F0-9]{8,17}$"
    ConstraintDescription: "The Route Table ID must be a valid ID starting with 'rtb-' followed by 8 to 17 hexadecimal characters."
  PublicSubnetId:
    Default: "subnet-1234567890abcdef0"
    Description: "Subnet Id."
    Type: String
    AllowedPattern: "^subnet-[a-fA-F0-9]{8,17}$"
    ConstraintDescription: "The Subnet ID must be a valid ID starting with 'subnet-' followed by 8 to 17 hexadecimal characters."

Resources:
  ###################################### Nat Gateway EIP ###########################################
  # Elastic IP for NAT Gateway
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-eip${CiBuild}"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA

  # NAT Gateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-natgw${CiBuild}"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
  RouteNATGateway:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId: !Ref PrivateRouteTableId
        DestinationCidrBlock: '0.0.0.0/0'
        NatGatewayId: !GetAtt NatGateway.NatGatewayId
Outputs:
  ###################################### Nat Gateway ###############################################
  NatGatewayId:
    Description: Nat Gateway Id
    Value: !GetAtt NatGateway.NatGatewayId
  ElasticIp:
    Description: Nat Gateway Elastic IP
    Value: !GetAtt NatGatewayEIP.PublicIp