AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Security Group within a specified VPC

Metadata:
  TemplateName: security-group.yaml
  TemplateType: Security Group
  Description: >-
    This CloudFormation template defines a security group within a specified VPC.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 08, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.    
    VpcId: The ID of the VPC. Must be in the form 'vpc-' followed by alphanumeric characters.
    SecurityGroupBaseName: The base name for the security group. Can contain alphanumeric characters, hyphens, and underscores.
    SecurityGroupDescription: The description for the security group. Can contain alphanumeric characters, spaces, hyphens, underscores, and punctuation.

    Resources:
      SecurityGroup: An AWS EC2 Security Group with properties for GroupName, GroupDescription, VpcId, and Tags.

    Outputs:
      SecurityGroupId: The ID of the created EC2 Security Group.
      SecurityGroupVpcId: The VPC ID of the created EC2 Security Group.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## Security Group ############################################
      - Label:
          default: "Security Group:"
        Parameters:
          - VpcId
          - SecurityGroupBaseName
          - SecurityGroupDescription
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Security Group ############################################
      VpcId:
        default: "The ID of the VPC."
      SecurityGroupBaseName:
        default: "Base name for the security group."
      SecurityGroupDescription:
        default: "Description of the security group."


Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### VPC ####################################################
  VpcId:
    Description: "The ID of the VPC."
    Type: String
    AllowedPattern: "^vpc-[a-zA-Z0-9]+$"
    ConstraintDescription: "The VPC ID must be in the form 'vpc-' followed by alphanumeric characters."

  ###################################### Security Group ############################################
  SecurityGroupBaseName:
    Default: ec2-sg
    Description: "The Security Group base name to be used as a resource name."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_-]+$"
    ConstraintDescription: "The Security Group base name can only contain alphanumeric characters, hyphens, and underscores."

  SecurityGroupDescription:
    Default: "The Security Group to be used as a resource name."
    Description: "The Security Group description to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9 _.,-]+$"
    ConstraintDescription: "The Security Group description can only contain alphanumeric characters, spaces, hyphens, underscores, and punctuation."

Resources:
  ###################################### Security Group ############################################
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${SecurityGroupBaseName}${CiBuild}'
      GroupDescription: !Ref SecurityGroupDescription
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${SecurityGroupBaseName}${CiBuild}'
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
          
Outputs:
  ###################################### Security Group ############################################
  SecurityGroupId:
    Description: EC2 Security Group Id
    Value: !GetAtt SecurityGroup.GroupId
  SecurityGroupVpcId:
    Description: VPC Id of EC2 Security Group
    Value: !GetAtt SecurityGroup.VpcId
