AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Subnet

Metadata:
  TemplateName: subnet.yaml
  TemplateType: Subnet (public / private)
  Description: >
    This CloudFormation template creates a VPC subnet with optional IPv6 support and public/private subnet configuration.
    It includes parameters for project and environment details, GitHub attributes, and subnet-specific configurations.
    The template also defines conditions for public subnet and IPv6 CIDR block, and resources for subnet, IPv6 CIDR block,
    internet gateway attachment, route table, and route table association.
    Outputs include subnet ID, availability zone, CIDR block, network ACL association ID, and route table association ID.
    The template is designed to be used as a nested stack in a VPC template.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 06, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    VpcId: The ID of the VPC.
    SubnetCidrBlock: Subnet CIDR Block.
    InternetGatewayId: The ID of the attached Internet Gateway.
    EnableIPV6Cidr: Indicates if IPv6 CIDR is enabled.
    IPV6SubnetPart: The IPv6 subnet part.
    IPV6VpcPart: The IPv6 VPC part


    Conditions:
      IsPublicSubnet: Checks if the subnet is public.
      EnableIPV6Cidr: Checks if IPv6 CIDR is enabled.

    Resources:
      Subnet: Creates an AWS::EC2::Subnet resource with specified properties and tags.
      IPv6CidrBlock: Creates an AWS::EC2::VPCCidrBlock resource for IPv6 CIDR block if enabled.
      AttachInternetGateway: Creates an AWS::EC2::VPCGatewayAttachment resource to attach the internet gateway if the subnet is public.
      RouteTable: Creates an AWS::EC2::RouteTable resource with specified properties and tags.
      RouteTableAssociation: Creates an AWS::EC2::SubnetRouteTableAssociation resource to associate the subnet with the route table.

    Outputs:
      SubnetId: The ID of the created subnet.
      SubnetAvailabilityZone: The availability zone of the subnet.
      SubnetAvailabilityZoneId: The availability zone ID of the subnet.
      SubnetCidrBlock: The CIDR block of the subnet.
      RouteTableId: The ID of the route table associated with the subnet.
      SubnetNetworkAclAssociationId: The network ACL association ID of the subnet.
      SubnetRouteTableAssociationId: The route table association ID of the subnet.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## VPC #######################################################
      - Label:
          default: "VPC Configuration:"
        Parameters:
          - VpcId
          - SubnetCidrBlock
          - NetworkAclId
          - AvaliabilityZone
          - EnableIPV6Cidr
          - IPV6SubnetPart
          - IPV6VpcPart
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Subnet Attributes #########################################
      VpcId:
        default: "ID of the VPC."
      SubnetCidrBlock:
        default: "IPv4 CIDR block for the subnet."
      NetworkAclId:
        default: "ID of the network ACL."
      AvaliabilityZone:
        default: "Availability Zone for the subnet."
      EnableIPV6Cidr:
        default: "Enable IPv6 CIDR block."
      IPV6SubnetPart:
        default: "IPv6 subnet part."
      IPV6VpcPart:
        default: "IPv6 VPC part."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Subnet ####################################################
  VpcId:
    Description: "The ID of the VPC."
    Type: String

  SubnetCidrBlock:
    Default: "10.0.0.0/16"
    Description: "Subnet CIDR Block."
    Type: String
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "The VPC CIDR Block must be in the form x.x.x.x/x."

  NetworkAclId:
    Description: "The ID of the Network ACL."
    Type: String
    AllowedPattern: "^acl-[a-zA-Z0-9]+$"
    ConstraintDescription: "The Network ACL ID must be in the form 'acl-' followed by alphanumeric characters."

  AvaliabilityZone:
    Default: "us-east-1a"
    Description: "The Availability Zone where the subnet will be created."
    Type: String
    AllowedValues: ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d", "us-east-1e", "us-east-1f", "us-east-1g", "us-east-1h"]

  AZ: 
    Description:  "The Availability Zone suffix to be used in the AZ name."
    Type: String
    AllowedValues: ["az1","az2","az3","az4"]

  InternetGatewayId:
    Default: ""
    Description: "The ID of the attached Internet Gateway."
    Type: String
    AllowedPattern: "^$|^igw-[a-zA-Z0-9]+$"
    ConstraintDescription: "The Internet Gateway ID must be in the form 'igw-' followed by alphanumeric characters."

  EnableIPV6Cidr:
    Default: "false"
    Description: "Enable IPV6 Cidr for this Subnet ?."
    Type: String
    AllowedValues:
      - "true"
      - "false"

  IPV6SubnetPart:
    Default: ""
    Description: "IPv6 subnet part."
    Type: String
    AllowedPattern: "^$|^(\\d{1,3})\\:\\:[0-9a-fA-F]{0,4}\\/64$"
    ConstraintDescription: "The IPv6 subnet part must be in the form 'x::/64' where x is a hexadecimal number."

  IPV6VpcPart:
    Default: ""
    Description: "IPv6 VPC part."
    Type: String

######################################## Conditional ###############################################
Conditions:
  IsPublicSubnet: !Not [!Equals [!Ref InternetGatewayId, ""]]
  IsIPV6CidrEnabled: !Equals [!Ref EnableIPV6Cidr, "true"]

Resources:
  ###################################### Subnet ####################################################
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref SubnetCidrBlock
      MapPublicIpOnLaunch: !If
        - IsPublicSubnet
        - true
        - false
      AvailabilityZone: !Ref AvaliabilityZone
      Ipv6CidrBlock:  !If 
        - IsIPV6CidrEnabled
        - !Sub "${IPV6VpcPart}${IPV6SubnetPart}"
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !If
          - IsPublicSubnet
          - !Sub "${ProjectName}-pub-sn-${AZ}${CiBuild}"
          - !Sub "${ProjectName}-pvt-sn-${AZ}${CiBuild}"
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Condition: IsIPV6CidrEnabled
    Properties:
      VpcId: !Ref VpcId
      AmazonProvidedIpv6CidrBlock: true
  SubnetNetworkAclAssociation:
     Type: AWS::EC2::SubnetNetworkAclAssociation
     Properties:
       SubnetId:
         Ref: Subnet
       NetworkAclId: !Ref NetworkAclId
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !If
        - IsPublicSubnet
        - !Sub "${ProjectName}-pub-rt${CiBuild}"
        - !Sub "${ProjectName}-pvt-rt${CiBuild}"
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
  DefaultRoute:
    Condition: IsPublicSubnet
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGatewayId
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
Outputs:
  VpcId:
    Description: VPC Id of the Subnet.
    Value: !GetAtt Subnet.VpcId
  SubnetId:
    Description: Subnet Id
    Value: !Ref Subnet
  AvailabilityZone:
    Description: Subnet Availability Zone
    Value: !GetAtt Subnet.AvailabilityZone
  AvailabilityZoneId:
    Description: Subnet Availability ZoneId
    Value: !GetAtt Subnet.AvailabilityZoneId
  CidrBlock:
    Description: Subnet CI/DR Block
    Value: !GetAtt Subnet.CidrBlock
  IPV6CidrBlocks:
    Condition: IsIPV6CidrEnabled
    Description: Subnet IPV6 CI/DR Blocks
    Value: !Select [0, !GetAtt Subnet.Ipv6CidrBlocks]
  NetworkAclAssociationId:
    Description: Subnet Network Acl Association Id
    Value: !GetAtt Subnet.NetworkAclAssociationId
  RouteTableId:
    Description: Subnet Route Table Id
    Value: !Ref RouteTable
  RouteTableAssociationId:
    Description: Subnet Route Table Association Id
    Value: !Ref RouteTableAssociation