AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Glue Job Trigger.

Metadata:
  TemplateName: glue-trigger.yaml
  TemplateType: Glue Trigger
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## KMS Key ###################################################
      - Label:
          default: "KMS Configuration:"
        Parameters:
          - KmsMasterKeyArn
      ################################## Glue Trigger ##############################################
      - Label:
          default: "CloudWatch Log Group Configuration:"
        Parameters:
          - LogGroupServiceName
          - LogGroupBaseName
          - LogGroupClass
          - LogRetentionInDays

    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## KMS Key ###################################################
      KmsMasterKeyArn:
        default: "KMS Master Key Arn."
      ################################## CloudWatch Log group ######################################
      LogGroupServiceName:
        default: "Service name for the CloudWatch Log Group."
      LogGroupBaseName:
        default: "Base name of the CloudWatch Log Group."
      LogGroupClass:
        default: "Class of the CloudWatch Log Group."
      LogRetentionInDays:
        default: "Retention period of the CloudWatch Log Group."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: 1
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### KMS #######################################################
  KmsMasterKeyArn:
    Default: ""
    Description: "The KMS master key alias to be used for server-side encryption."
    Type: String
    AllowedPattern: "^$|^(arn:(aws[a-zA-Z-]*)?:[a-z0-9-.]+:.*)|()$"
    ConstraintDescription: "KMS Key Arn should be a valid KMS Key Arn if provided."

  ###################################### CloudWatch Log Group ######################################
  LogGroupServiceName:
    Default: "lambda"
    Description: "Specifies the service for the log group."
    Type: String
    AllowedValues:
    - lambda

  LogGroupBaseName:
    Default: "log-group"
    Description: "Specifies the name for the Glue Job."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The name must be 5 to 20 characters long and consist only of lowercase letters, numbers, or hyphens."

  LogGroupClass:
    Type: String
    Default: "INFREQUENT_ACCESS"
    Description: "Specifies the log group class."
    AllowedValues:
      - STANDARD
      - INFREQUENT_ACCESS
    ConstraintDescription: "The value must be either STANDARD or Log INFREQUENT_ACCESS."

  LogRetentionInDays:
    Type: Number
    Default: 7
    Description: "Specifies the number of days to retain log events."
    MinValue: 1
    MaxValue: 30
    ConstraintDescription: "The value must be between 1 and 30."
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30

Conditions:
  KmsEncryptionEnabled: !Not [!Equals [!Ref KmsMasterKeyArn, ""]]

Resources:
  ###################################### CloudWatch Log ############################################
  CloudWatchLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::Logs::LogGroup
    Properties:
      # DataProtectionPolicy: Json
      # FieldIndexPolicies: 
      #   - 
      #   Key: Value
      KmsKeyId: !If [KmsEncryptionEnabled, !Ref KmsMasterKeyArn, !Ref "AWS::NoValue"]
      LogGroupClass: !Ref LogGroupClass
      LogGroupName: !Sub "/aws/${LogGroupServiceName}/${ProjectName}-${LogGroupBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      RetentionInDays: !Ref LogRetentionInDays
      Tags: 
      - Key: "ProjectName"
        Value: !Ref ProjectName
      - Key: "Environment"
        Value: !Ref Environment
      - Key: "GitHubRef"
        Value: !Ref GitHubRef
      - Key: "GitHubURL"
        Value: !Ref GitHubURL
      - Key: "GitHubWFRunNumber"
        Value: !Ref GitHubWFRunNumber
      - Key: "GitHubSHA"
        Value: !Ref GitHubSHA
      - Key: "GitHubRepository"
        Value: !Ref GitHubRepository
      - Key: "CiBuild"
        Value: !Ref CiBuild

Outputs:
  LogGroupArn:
    Description: The arn of the CloudWatch LogGroup.
    Value: !GetAtt CloudWatchLogGroup.Arn
