AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Lambda Function

Metadata:
  TemplateName: lambda-function.yaml
  TemplateType: Lambda Function
  TemplateVersion: 1.0.0
  Description: >-
    This CloudFormation template defines a Lambda Function.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 01, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    CodeRepositoryS3Bucket: The GitHub Code Repository URL.
    LambdaLayerBaseName:   Base name of the Lambda layer.
    LambdaLayerDescription: Description of the Lambda layer.

    Conditions:
      EnableIPV6Cidr: Checks if IPv6 CIDR is enabled.

    Resources:
      LambdaLayer: Creates a Lambda Layer with the specified properties.

    Outputs:
      LambdaLayerVesion: The version of the Lambda layer
      LambdaLayerArn: The ARN of the lLmbda layer

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - CiBuild
      ################################## Code Repository ###########################################
      - Label:
          default: "Code Repository Bucket:"
        Parameters:
          - CodeRepositoryS3Bucket
      ################################## Lambda ####################################################
      - Label:
          default: "Lambda Layer Configuration:"
        Parameters:
          - LambdaLayerBaseName
          - LambdaLayerDescription
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## Code Repository ###########################################
      CodeRepositoryS3Bucket:
        default: "S3 bucket for the code repository."
      ################################## Lambda ####################################################
      LambdaLayerBaseName:
        default: "Base name of the Lambda layer."
      LambdaLayerDescription:
        default: "Description of the Lambda layer."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String



  ###################################### Code Repository ###########################################
  CodeRepositoryS3Bucket:
    Default: "subhamay-aws-cfn-nested-stack-templates-us-east-1"
    Description: "The GitHub Code Repository URL."
    Type: String
    AllowedPattern: "^[a-z0-9.-]{3,63}$"
    ConstraintDescription: "The S3 bucket name must be between 3 and 63 characters long, and can only contain lowercase letters, numbers, dots, and hyphens." ###################################### GitHub Attributes #########################################
  
  ###################################### Lambda ####################################################
  LambdaLayerBaseName:
    Default: layer
    Description: "The base name for the Lambda function. The region and environment will be appended as a suffix by the template."
    Type: String
    MinLength: "5"
    MaxLength: "40"
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
    ConstraintDescription: "The name must be between 5 and 40 characters long, start with a letter, and may include letters, numbers, or hyphens."

  LambdaLayerDescription:
    Default: The Processing Lambda Function.
    Description: "A description of the Lambda function."
    Type: String
    MaxLength: "200"
    AllowedPattern: "^$|^[A-Z][a-zA-Z0-9 .,]*$"
    ConstraintDescription: "The description must be 0–200 characters long, start with an uppercase letter, and may include letters, numbers, spaces, dots, or commas."

Resources:
  ###################################### Lambda ####################################################
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${ProjectName}-${LambdaLayerBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      Description: !Ref LambdaLayerDescription
      CompatibleArchitectures: ["x86_64", "arm64"]
      Content:
        S3Bucket: !Ref CodeRepositoryS3Bucket
        S3Key: !Sub "${ProjectName}/${LambdaLayerBaseName}.zip"
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
Outputs:
  ###################################### Lambda Layer ##############################################
  LambdaLayerArn:
    Description: Lambda Layer Arn
    Value: !GetAtt LambdaLayer.LayerVersionArn 