AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template To Create A SNS Topic subscription for Email/SQS/Lambda/HTTPS endpoint.

Metadata:
  TemplateName: sns-subscription.yaml
  TemplateType: SNS Topic subscription
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    SNSTopicArn: The ARN of the SNS Topic.
    EmailAddress: The email address to subscribe to the SNS topic.
    SqsQueueArn: The ARN of the SQS Queue to subscribe to the SNS topic.
    LambdaFunctionArn: The ARN of the Lambda function to subscribe to the SNS topic.
    HttpEndpoint: The HTTP endpoint to subscribe to the SNS topic.

  Conditions:
    EmailSubscription: Checks if EmailAddress is provided.
    SqsSubscription: Checks if SqsQueueArn is provided.
    LambdaSubscription: Checks if LambdaFunctionArn is provided.
    HttpEndpointSubscription: Checks if HttpEndpoint is provided.

  Resources:
    EmailSubscription: Creates an SNS subscription for the provided email address.
    SqsSubscription: Creates an SNS subscription for the provided SQS queue.
    LambdaSubscription: Creates an SNS subscription for the provided Lambda function.
    HttpsSubscription: Creates an SNS subscription for the provided HTTP endpoint with a delivery policy.

  Outputs:
    EmailSubscriptionArn: The ARN of the SNS Topic Email subscription.
    SqsSubscriptionArn: The ARN of the SNS Topic SQS subscription.
    LambdaSubscriptionArn: The ARN of the SNS Topic Lambda function subscription.
    HttpsSubscriptionArn: The ARN of the SNS Topic HTTP endpoint subscription.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## SNS #######################################################
      - Label:
          default: "SNS Configuration:"
        Parameters:
          - SNSTopicArn
      ################################## Subscriptions #############################################
      - Label:
          default: "Subscriptions:"
        Parameters:
          - EmailAddress
          - SqsQueueArn
          - LambdaFunctionArn
          - HttpEndpoint

    ParameterLabels:
      ################################## SNS Topic #################################################
      SNSTopicArn:
        default: "ARN of the SNS topic."
      ################################## SNS Subscription ##########################################
      EmailAddress:
        default: "Email address for subscribing to the SNS topic."
      SqsQueueArn:
        default: "ARN of the SQS queue for subscribing to the SNS topic."
      LambdaFunctionArn:
        default: "ARN of the Lambda function for subscribing to the SNS topic."
      HttpEndpoint:
        default: "HTTP endpoint for subscribing to the SNS topic."

Parameters:
  ###################################### SNS #######################################################
  SNSTopicArn:
    Default: "arn:aws:sns:us-east-1:123456789012:sns-topic-name"
    Description: "The ARN of the SNS Topic."
    Type: String
    MinLength: "20"
    MaxLength: "2048"
    AllowedPattern: "^arn:aws:sns:[a-z0-9-]+:[0-9]{12}:[a-zA-Z0-9-_]+$"
    ConstraintDescription: "The ARN must be a valid SNS topic ARN."
  
  ###################################### Subscriptions #############################################
  EmailAddress:
    Default: "example@example.com"
    Description: "The email address to subscribe to the SNS topic."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    ConstraintDescription: "The email address must be a valid email address."
  
  SqsQueueArn:
    Default: "arn:aws:sqs:us-east-1:123456789012:sqs-queue-name"
    Description: "The ARN of the SQS Queue to subscribe to the SNS topic."
    Type: String
    MinLength: "20"
    MaxLength: "2048"
    AllowedPattern: "^arn:aws:sqs:[a-z0-9-]+:[0-9]{12}:[a-zA-Z0-9-_]+$"
    ConstraintDescription: "The ARN must be a valid SQS queue ARN."
  
  LambdaFunctionArn:
    Default: "arn:aws:lambda:us-east-1:123456789012:function:sqs-queue-name"
    Description: "The ARN of the Lambda function to subscribe to the SNS topic."
    Type: String
    MinLength: "20"
    MaxLength: "2048"
    AllowedPattern: "^arn:aws:lambda:[a-z0-9-]+:[0-9]{12}:function:[a-zA-Z0-9-_]+$"
    ConstraintDescription: "The ARN must be a valid Lambda function ARN."
  
  HttpEndpoint:
    Default: "https://example.com"
    Description: "The HTTP endpoint to subscribe to the SNS topic."
    Type: String
    AllowedPattern: "^(http|https)://.*$"
    ConstraintDescription: "The HTTP endpoint must be a valid URL."

Conditions:
  EmailSubscription: !Not [!Equals [!Ref EmailAddress, "example@example.com"]]
  SqsSubscription: !Not [!Equals [!Ref SqsQueueArn, "arn:aws:sqs:us-east-1:123456789012:sqs-queue-name"]]
  LambdaSubscription: !Not [!Equals [!Ref LambdaFunctionArn, "arn:aws:lambda:us-east-1:123456789012:function:sqs-queue-name"]]
  HttpEndpointSubscription: !Not [!Equals [!Ref HttpEndpoint, "https://example.com"]]

Resources:
  ###################################### SNS Subscription ##########################################
  EmailSubscription:
    Condition: EmailSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopicArn
      Endpoint: !Ref EmailAddress
  SqsSubscription:
    Condition: SqsSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSTopicArn
      Endpoint: !Ref SqsQueueArn
  LambdaSubscription:
    Condition: LambdaSubscription
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref SNSTopicArn
      Endpoint: !Ref LambdaFunctionArn
  HttpsSubscription:
    Type: AWS::SNS::Subscription
    Condition: HttpEndpointSubscription
    Properties:
      TopicArn: !Ref SNSTopicArn
      Endpoint: !Ref HttpEndpoint
      Protocol: https
      DeliveryPolicy:
        healthyRetryPolicy:
          numRetries: 20
          minDelayTarget: 10
          maxDelayTarget: 30
          numMinDelayRetries: 3
          numMaxDelayRetries: 17
          numNoDelayRetries: 0
          backoffFunction: exponential

Outputs:
  EmailSubscriptionArn:
    Condition: EmailSubscription
    Description: The Arn of the SNS Topic Email subscription.
    Value: !Ref EmailSubscription
  SqsSubscriptionArn:
    Condition: SqsSubscription
    Description: The Arn of the SNS Topic SQS subscription.
    Value: !Ref SqsSubscription
  LambdaSubscriptionArn:
    Condition: LambdaSubscription
    Description: The Arn of the SNS Topic Lambda function subscription.
    Value: !Ref LambdaSubscription
  HttpsSubscriptionArn:
    Condition: HttpEndpointSubscription
    Description: The Arn of the SNS Topic HTTP endpoint subscription.
    Value: !Ref HttpsSubscription
