AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Glue Job Trigger.

Metadata:
  TemplateName: glue-trigger.yaml
  TemplateType: Glue Trigger
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## CloudWatch Alarm ##########################################
      - Label:
          default: "Rest API Configuration:"
        Parameters:
        - RestApiId
        - ProtocolType
        - AuthorizationType
        - HttpMethod
        - ResourceId
        - LambdaFunctionArn
        - LambdaInvokeTriggeredByRestApi
        - ResourcePath
    ParameterLabels:
      ################################## API Gateway ###############################################
      RestApiId:
        default: "The ID of the Rest API."
      ProtocolType:
        default: "The protocol type for the API Gateway."
      AuthorizationType:
        default: "The authorization type for the API Gateway."
      HttpMethod:
        default: "The HTTP method for the API Gateway."
      ResourceId:
        default: "The ID of the resource for the API Gateway."
      LambdaFunctionArn:
        default: "The ARN of the Lambda function to be integrated with the API Gateway."
      LambdaInvokeTriggeredByRestApi:
        default: "Indicates whether the Lambda function is triggered by the API Gateway."
      ResourcePath:
        default: "The path part of the resource for the API Gateway."
Parameters:
  ###################################### Rest API Method ###########################################
  RestApiId:
    Default: "pfx6j9dopb"
    Description: "The ID of the Rest API."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9]*$"
    ConstraintDescription: "The Rest API ID must be an alphanumeric string."

  ProtocolType:
    Default: HTTP
    Description: "The protocol type for the API Gateway."
    Type: String
    AllowedValues: ["HTTP", "WEBSOCKET", "REST"]
    ConstraintDescription: "The protocol type must be HTTP or WEBSOCKET."

  AuthorizationType:
    Default: NONE
    Description: "The authorization type for the API Gateway."
    Type: String
    AllowedValues: ["NONE", "AWS_IAM", "CUSTOM", "COGNITO_USER_POOLS"]
    ConstraintDescription: "The authorization type must be NONE, AWS_IAM, CUSTOM, or COGNITO_USER_POOLS."

  HttpMethod:
    Default: GET
    Description: "The HTTP method for the API Gateway."
    Type: String
    AllowedValues: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "ANY"]
    ConstraintDescription: "The HTTP method must be one of GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, or ANY."

  ResourceId: 
    Default: "dvlvfeeqb2"
    Description: "The ID of the resource for the API Gateway."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9]*$"
    ConstraintDescription: "The resource ID must be an alphanumeric string."

  LambdaFunctionArn:
    Default: ""
    Description: "The ARN of the Lambda function to be integrated with the API Gateway."
    Type: String

  LambdaInvokeTriggeredByRestApi:
    Default: "false"
    Description: "Indicates whether the Lambda function is triggered by the API Gateway."
    Type: String
    AllowedValues: ["false", "true"]
    ConstraintDescription: "The value must be either 'true' or 'false."

  ResourcePath:
    Default: ""
    Description: "The path part of the resource for the API Gateway."
    Type: String
    AllowedPattern: "^$|^[a-zA-Z0-9]*$"
    ConstraintDescription: "The resource path part must be an alphanumeric string."

Conditions:
  IsRestAPi: !Equals [!Ref ProtocolType, "REST"]
  # IsHttpOrWebsocket: !Or [!Equals [!Ref ProtocolType, "HTTP"], !Equals [!Ref ProtocolType, "WEBSOCKET"]]
  IntegrationTypeLambda: !Not [!Equals [!Ref LambdaFunctionArn, ""]]
  EnableApiGatewayTarget: !Not [!Equals [!Ref LambdaInvokeTriggeredByRestApi, ""]]

Resources:
  ###################################### API Gateway Resp API #####################################$
  # APIGatewayApi:
  #   Condition: IsHttpOrWebsocket
  #   Type: AWS::ApiGatewayV2::Api
  #   Properties:
  #     # ApiKeySelectionExpression: String
  #     # BasePath: String
  #     # Body: Json
  #     # BodyS3Location: 
  #     #   BodyS3Location
  #     # CorsConfiguration: 
  #     #   Cors
  #     # CredentialsArn: String
  #     Description: !Ref ApiDescription
  #     # DisableExecuteApiEndpoint: Boolean
  #     # DisableSchemaValidation: Boolean
  #     # FailOnWarnings: Boolean
  #     Name: !Sub "${ProjectName}-${ApiBaseName}-${Environment}-${AWS::Region}${CiBuild}"
  #     ProtocolType: !Ref ProtocolType
  #     # RouteKey: String
  #     # RouteSelectionExpression: String
  #     # Tags: 
  #     # - Key: ProjectName
  #     #   Value: !Ref ProjectName
  #     # - Key: Environment
  #     #   Value: !Ref Environment
  #     # - Key: GitHubRef
  #     #   Value: !Ref GitHubRef
  #     # - Key: GitHubURL
  #     #   Value: !Ref GitHubURL
  #     # - Key: GitHubWFRunNumber
  #     #   Value: !Ref GitHubWFRunNumber
  #     # - Key: GitHubSHA
  #     #   Value: !Ref GitHubSHA
  #     # - Key: GitHubRepository
  #     #   Value: !Ref GitHubRepository
  #     # - Key: CiBuild
  #     #   Value: !Ref CiBuild
  #     # Target: String
  #     # Version: String

  APIGatewayRestApiMethod:
    Condition: IsRestAPi
    Type: AWS::ApiGateway::Method
    Properties:
      # ApiKeyRequired: Boolean
      # AuthorizationScopes: 
        # - String
      AuthorizationType: !Ref AuthorizationType
      # AuthorizerId: String
      HttpMethod: !Ref HttpMethod
      Integration: 
        !If 
          - IntegrationTypeLambda
          - 
            Type: AWS_PROXY
            IntegrationHttpMethod: POST
            Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - !Ref AWS::NoValue

      # MethodResponses: 
      #   - MethodResponse
      # OperationName: String
      # RequestModels: 
      #   Key: Value
      # RequestParameters: 
      #   Key: Value
      # RequestValidatorId: String
      ResourceId: !Ref ResourceId
      RestApiId: !Ref RestApiId

  LambdaInvokePermissionApiGW:
    Condition: EnableApiGatewayTarget
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref LambdaFunctionArn
      Principal: "apigateway.amazonaws.com"
      # SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/POST/${ResourcePath}"
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/${HttpMethod}/${ResourcePath}"
Outputs:
  # ApiEndpoint:
  #   Condition: IsHttpOrWebsocket
  #   Description: The endpoint URL of the API
  #   Value: !GetAtt  APIGatewayApi.ApiEndpoint
  # ApiId:
  #   Condition: IsHttpOrWebsocket
  #   Description: The API ID
  #   Value: !Ref APIGatewayApi
  RestApiMethodId:
    Condition: IsRestAPi
    Description: The rest api method ID
    Value: !Ref APIGatewayRestApiMethod