AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Glue Job Trigger.

Metadata:
  TemplateName: glue-trigger.yaml
  TemplateType: Glue Trigger
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Dec 31, 2024 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - CiBuild
      ################################## CloudWatch Alarm ##########################################
      - Label:
          default: "Rest API Configuration:"
        Parameters:
        - ApiBaseName
        - ApiDescription
        - ProtocolType
        - EndpointType
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## API Gateway ###############################################
      ApiBaseName:
        default: "Base name of the API Gateway Api."
      ApiDescription:
        default: "Description of the API Gateway Api."
      ProtocolType:
        default: "Protocol type of the API Gateway Api."
      EndpointType:
        default: "Endpoint type of the API Gateway Api."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### Api Gateway ###############################################
  ApiBaseName:
    Default: "api01"
    Description: "Base name of the API Gateway."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  ApiDescription:
    Default: "API Gateway for the application."
    Description: "Description of the API Gateway."
    Type: String

  ProtocolType:
    Default: HTTP
    Description: "The protocol type for the API Gateway."
    Type: String
    AllowedValues: ["HTTP", "WEBSOCKET", "REST"]
    ConstraintDescription: "The protocol type must be HTTP or WEBSOCKET."

  EndpointType:
    Default: REGIONAL
    Description: "The endpoint type for the API Gateway."
    Type: String
    AllowedValues: ["REGIONAL", "EDGE", "PRIVATE"]
    ConstraintDescription: "The endpoint type must be REGIONAL, EDGE or PRIVATE."

Conditions:
  IsRestAPi: !Equals [!Ref ProtocolType, "REST"]
  IsHttpOrWebsocket: !Or [!Equals [!Ref ProtocolType, "HTTP"], !Equals [!Ref ProtocolType, "WEBSOCKET"]]

Resources:
  ###################################### API Gateway Resp API #####################################$
  APIGatewayApi:
    Condition: IsHttpOrWebsocket
    Type: AWS::ApiGatewayV2::Api
    Properties:
      # ApiKeySelectionExpression: String
      # BasePath: String
      # Body: Json
      # BodyS3Location: 
      #   BodyS3Location
      # CorsConfiguration: 
      #   Cors
      # CredentialsArn: String
      Description: !Ref ApiDescription
      # DisableExecuteApiEndpoint: Boolean
      # DisableSchemaValidation: Boolean
      # FailOnWarnings: Boolean
      Name: !Sub "${ProjectName}-${ApiBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      ProtocolType: !Ref ProtocolType
      # RouteKey: String
      # RouteSelectionExpression: String
      # Tags: 
      # - Key: ProjectName
      #   Value: !Ref ProjectName
      # - Key: Environment
      #   Value: !Ref Environment
      # - Key: GitHubRef
      #   Value: !Ref GitHubRef
      # - Key: GitHubURL
      #   Value: !Ref GitHubURL
      # - Key: GitHubWFRunNumber
      #   Value: !Ref GitHubWFRunNumber
      # - Key: GitHubSHA
      #   Value: !Ref GitHubSHA
      # - Key: GitHubRepository
      #   Value: !Ref GitHubRepository
      # - Key: CiBuild
      #   Value: !Ref CiBuild
      # Target: String
      # Version: String

  APIGatewayRestApi:
    Condition: IsRestAPi
    Type: AWS::ApiGateway::RestApi
    Properties:
      # ApiKeySourceType: String
      # BinaryMediaTypes: 
      #   - String
      # Body: Json
      # BodyS3Location: 
      #   S3Location
      # CloneFrom: String
      Description: !Ref ApiDescription
      # DisableExecuteApiEndpoint: Boolean
      EndpointConfiguration: 
        Types: 
          - !Ref EndpointType
        # VpcEndpointIds: 
        #   - String

      # FailOnWarnings: Boolean
      # MinimumCompressionSize: Integer
      # Mode: String
      Name: !Sub "${ProjectName}-${ApiBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      # Parameters: 
      #   Key: Value
      # Policy: Json
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

Outputs:
  ApiId:
    Condition: IsHttpOrWebsocket
    Description: The API ID
    Value: !Ref APIGatewayApi
  RootResourceId:
    Condition: IsRestAPi
    Description: The root resource id of the API
    Value: !GetAtt  APIGatewayRestApi.RootResourceId
  RestApiId:
    Condition: IsRestAPi
    Description: The API ID
    Value: !GetAtt APIGatewayRestApi.RestApiId