AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a Secret Manager Secret

Metadata:
  TemplateName: secret-manager.yaml
  TemplateType: Secret Manager
  Description: >
    This CloudFormation template creates an AWS Secrets Manager secret with various configurable parameters.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0  Jan 13, 2025  --  Initial Version
  StepsToTest: Manually verify the Stack.
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias used for server-side encryption. Must be between 5 and 20 characters, containing only alphanumeric characters and dashes.
    SecretBaseName: The base name of the secret. Must be between 5 and 50 characters, containing only alphanumeric characters and dashes.
    SecretDescription: The description of the secret. Must be between 5 and 500 characters.
    GenerateSecretString: A flag indicating whether to auto-generate the secret string. Must be "true" or "false".

    Conditions:
      AutoGenerateSecretString: A condition that checks if the GenerateSecretString parameter is set to "true".

    Resources:
      SecretManagerSecret: > 
        An AWS Secrets Manager secret with properties such as description, KMS key ID, name, and tags. If AutoGenerateSecretString is true, it 
        will generate a secret string with specified properties.


    Outputs:
      SecretManagerSecretArn: The ARN of the created Secrets Manager secret.


  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## KMS #######################################################
      - Label:
          default: "KMS Configuration:"
        Parameters:
          - KmsMasterKeyAlias
      ################################## Secret Manager Configuration ##############################
      - Label:
          default: "Secret Manager Secret Configuration:"
        Parameters:
          - SecretBaseName
          - SecretDescription
          - GenerateSecretString

    ParameterLabels:
      #################################### Project Name and Environment #############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      #################################### GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      ################################## KMS #######################################################
      KmsMasterKeyAlias:
        default: "Alias for the KMS master key."
      ################################## Secret Manager Configuration ##############################
      SecretBaseName:
        default: "The base name of the secret."
      SecretDescription:
        default: "The description of the secret."
      GenerateSecretString:
        default: "A flag indicating whether to auto-generate the secret string."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: "5"
    MaxLength: "30"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: "1"
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number
 
  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."
 
  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: "10"
    MaxLength: "30"
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."
 
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### KMS #######################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: "5"
    MaxLength: "20"
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."

  ###################################### Secret Manager ############################################
  SecretBaseName:
    Default: "api-key"
    Description: "The Secret Base Name."
    Type: String
    MinLength: "5"
    MaxLength: "50"
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the Secret Base Name should be beteen 5 and 50 and can only contain alphanumeric characters and dash."

  SecretDescription:
    Default: "Secret Description"
    Description: "The Secret Description."
    Type: String
    MinLength: "5"
    MaxLength: "500"
    ConstraintDescription: "The length of the Secret Description should be beteen 5 and 500."

  GenerateSecretString:
    Default: "false"
    Description: "Generate Secret String."
    Type: String
    AllowedValues: ["true", "false"]
######################################## Conditional ###############################################
Conditions:
  AutoGenerateSecretString: !Equals [!Ref GenerateSecretString, "true"]   

Resources:
  ###################################### VPC #######################################################
  SecretManagerSecret:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref SecretDescription
      GenerateSecretString: !If 
        - AutoGenerateSecretString
        -
          GenerateStringKey: Password
          ExcludeCharacters: String
          ExcludeLowercase: true
          ExcludeNumbers: false
          ExcludePunctuation: false
          ExcludeUppercase: false
          IncludeSpace: false
          PasswordLength: 16
          RequireEachIncludedType: true
        - !Ref AWS::NoValue

      KmsKeyId: !Sub "alias/${KmsMasterKeyAlias}"
      Name: !Sub "${ProjectName}-${SecretBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      Tags: 
        - Key: Name
          Value: !Sub "${ProjectName}-${SecretBaseName}-${Environment}-${AWS::Region}${CiBuild}"
        - Key: CiBuild
          Value: !Ref CiBuild
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA

Outputs:
  ###################################### Secret Manager Secret #####################################
  SecretArn:
    Description: The ARN of the created Secret Manager Secret.
    Value: !Ref SecretManagerSecret