AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  CFN Nested Template to create a DynamoDB Table with or without KMS Encryption.

Metadata:
  TemplateName: dynamodb-table.yaml
  TemplateType: DynamoDB Table with KMS Encryption
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Nested Stack Templates Collection
  Modification History:
    - 1.0.0 - Feb 01, 2025 -- Initial Version
  StepsToTest: Manually verify the Stack
  StepsToCleanup: Stack delete command

  Parameters:
    ProjectName: The Project name to be used as a resource tag value.
    Environment: The Environment name to be used as a resource tag value.
    GitHubRef: GitHub Ref name to be used as a resource tag value.
    GitHubURL: GitHub URL to be used as a resource tag value.
    GitHubWFRunNumber: The Workflow run number to be used as a resource tag value.
    GitHubSHA: The sha value of the last commit to be used as a resource tag value.
    GitHubRepository: The GitHub Repository name to be used as a resource tag value.
    CiBuild: Ci Build of the feature branch to be appended to a resource name.
    KmsMasterKeyAlias: The KMS master key alias to be used for server-side encryption.
    TopicBaseName: The base name of the SNS topic. The topic name will be created by appending the environment and region.
    TopicDisplayName: The SNS topic display name.

  Conditions:
    UseKmsMasterKey: Determines if KMS Master Key should be used based on the KmsMasterKeyAlias parameter.

  Resources:
    SNSTopic: Creates an SNS Topic with the specified properties and tags.

  Outputs:
    SNSTopicArn: The Arn of the SNS Topic.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      ################################## Project Name and Environment ##############################
      - Label:
          default: "Project Name and Environment:"
        Parameters:
          - ProjectName
          - Environment
      ################################## GitHub Attributes #########################################
      - Label:
          default: "GitHub Attributes:"
        Parameters:
          - GitHubRef
          - GitHubURL
          - GitHubWFRunNumber
          - GitHubSHA
          - GitHubRepository
          - CiBuild
      ################################## KMS Key ###################################################
      - Label:
          default: "KMS Configuration:"
        Parameters:
          - KmsMasterKeyAlias
      ################################## SNS #######################################################
      - Label:
          default: "DynamoDB Configuration:"
        Parameters:
          - TableBaseName
          - PartitionKeyName
          - PartitionKeyType
          - SortKeyName
          - SortKeyType
          # - LocalSecondaryIndexes
          # - GlobalSecondaryIndexes
          - BillingMode
          - TableClass
          - TTLAttributeName
          - ReadCapacityUnits
          - WriteCapacityUnits
          - PointInTimeRecoveryEnabled
          - VpcEndpointId

    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Name of the Project."
      Environment:
        default: "Name of the Deployment Environment."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Reference Branch or Tag."
      GitHubURL:
        default: "URL of the GitHub Repository."
      GitHubWFRunNumber:
        default: "GitHub Workflow Execution Run Number."
      GitHubSHA:
        default: "GitHub Commit SHA."
      GitHubRepository:
        default: "Name of the GitHub Repository."
      CiBuild:
        default: "Continuous Integration Build Identifier."
      ################################## KMS Key ###################################################
      KmsMasterKeyAlias:
        default: "KMS Master Key Alias."
      ################################## DynamoDB ##################################################
      TableBaseName:
        default: "Base name for the DynamoDB Table."
      PartitionKeyName:
        default: "Name of the Partition Key."
      PartitionKeyType:
        default: "Type of the Partition Key."
      SortKeyName:
        default: "Name of the Sort Key."
      SortKeyType:  
        default: "Type of the Sort Key." 
      # LocalSecondaryIndexes:
      #   default: "Comma-separated list of LSIs in format IndexName,KeyName,KeyType." 
      # GlobalSecondaryIndexes:
      #   default: "Comma-separated list of GSIs in format IndexName,PartitionKeyName,PartitionKeyType,SortKeyName,SortKeyType."
      BillingMode:
        default: "Billing Mode for the Table."
      TableClass: 
        default: "Table Class for the Table."
      TTLAttributeName:
        default: "Name of the Time to Live (TTL) Attribute."
      ReadCapacityUnits:
        default: "Read Capacity Units for the Table."
      WriteCapacityUnits:
        default: "Write Capacity Units for the Table."
      PointInTimeRecoveryEnabled:
        default: "Enable or disable Point-in-Time Recovery for the Table."
      VpcEndpointId:
        default: "ID of the VPC Endpoint for the Table."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: app01-proj-1
    Description: "The Project name to be used as a resource tag value."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets, numbers, or dashes."

  Environment:
    Default: devl
    Description: "The Environment name to be used as a resource tag value."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"

  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref name to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-zA-Z0-9/_-]+$"
    ConstraintDescription: "The GitHub Ref Name can only contain alphanumeric characters, slashes, underscores, and hyphens."

  GitHubURL:
    Default: "https://github.com/owner/repository"
    Description: "GitHub URL to be used as a resource tag value."
    Type: String
    AllowedPattern: "^https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/?$"
    ConstraintDescription: "The GitHub URL must start with 'https://github.com/' and can only contain alphanumeric characters, dots, underscores, and hyphens."

  GitHubWFRunNumber:
    Default: 1
    Description: "The Workflow run number to be used as a resource tag value."
    Type: Number

  GitHubSHA:
    Default: "d3b07384d113edec49eaa6238ad5ff00f6fb3796"
    Description: "The sha value of the last commit to be used as a resource tag value."
    Type: String
    AllowedPattern: "^[a-fA-F0-9]{40}$"
    ConstraintDescription: "The SHA value must be a 40-character hexadecimal string."

  GitHubRepository:
    Default: 0001-repo01name-py-cft
    Description: "The GitHub Repository name to be used as a resource tag value."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "^\\d{4}-[a-z0-9]+(-[a-z]+)*$"
    ConstraintDescription: "The repository length should be between 10 and 30, must contain only lowercase letters, numbers, dashes, dots, and should start with a letter."

  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch to be appended to a resource name."
    Type: String

  ###################################### KMS Key ###################################################
  KmsMasterKeyAlias:
    Default: ""
    Description: "The KMS master key alias to be used for server-side encryption."
    Type: String
    ConstraintDescription: "The KMS Master Key Alias must not be empty."
    AllowedPattern: "^$|^[a-zA-Z0-9/_-]+$"

  ###################################### DynamoDB Table ############################################
  TableBaseName:
    Type: String
    Description: "The base name for the DynamoDB table. The region will be added as a suffix by the template."
    AllowedPattern: "^[a-zA-Z0-9-_]{3,255}$"
    ConstraintDescription: "The table name must be between 3 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)."

  PartitionKeyName:
    Type: String
    Default: "id"
    Description: "Name of the partition key attribute."
    AllowedPattern: "^[a-zA-Z0-9-_]{1,255}$"
    ConstraintDescription: "The partition key name must be between 1 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)."

  PartitionKeyType:
    Type: String
    Default: "S"
    AllowedValues: [S, N, B]
    Description: "Type of the partition key (String, Number, or Binary)."
    AllowedPattern: "^[S|N|B]$"
    ConstraintDescription: "The partition key type must be S, N, or B."

  SortKeyName:
    Type: String
    Default: ""
    Description: "Sort Key name (mandatory for LSIs, optional otherwise)."
    AllowedPattern: "^$|^[a-zA-Z0-9-_]{1,255}$"
    ConstraintDescription: "The sort key name must be between 1 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)." 

  SortKeyType:
    Type: String
    Default: "S"
    AllowedValues: [S, N, B]
    Description: "Type of the sort key (String, Number, or Binary)."
    AllowedPattern: "^[S|N|B]$"
    ConstraintDescription: "The sort key type must be S, N, or B." 

  # LocalSecondaryIndexes:
  #   Type: String
  #   Default: ""
  #   Description: "Comma-separated list of LSIs in format IndexName,KeyName,KeyType."
  #   AllowedPattern: "^$|^[a-zA-Z0-9-_]{1,255},[a-zA-Z0-9-_]{1,255},[S|N|B]$"
  #   ConstraintDescription: "The LSI name must be between 1 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)."

  # GlobalSecondaryIndexes:
  #   Type: String
  #   Default: ""
  #   Description: "Comma-separated list of GSIs in format IndexName,PartitionKeyName,PartitionKeyType,SortKeyName,SortKeyType."
  #   AllowedPattern: "^$|^[a-zA-Z0-9-_]{1,255},[a-zA-Z0-9-_]{1,255},[S|N|B],[a-zA-Z0-9-_]{1,255},[S|N|B]$"
  #   ConstraintDescription: "The GSI name must be between 1 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)."

  BillingMode:
    Type: String
    Default: "PAY_PER_REQUEST"
    AllowedValues: [PROVISIONED, PAY_PER_REQUEST]
    Description: "Billing mode: PROVISIONED or PAY_PER_REQUEST."
    ConstraintDescription: "The billing mode must be PROVISIONED or PAY_PER_REQUEST."

  TableClass:
    Type: String
    Default: "STANDARD"
    AllowedValues: [STANDARD, STANDARD_INFREQUENT_ACCESS]
    Description: "Table class: STANDARD or STANDARD_INFREQUENT_ACCESS."
    ConstraintDescription: "The table class must be STANDARD or STANDARD_INFREQUENT_ACCESS."

  TTLAttributeName:
    Type: String
    Default: ""
    Description: "Name of the TTL attribute (if any)."
    AllowedPattern: "^$|^[a-zA-Z0-9-_]{1,255}$"
    ConstraintDescription: "The TTL attribute name must be between 1 and 255 characters long, and can only contain alphanumeric characters, hyphens (-), and underscores (_)."
  
  ReadCapacityUnits:
    Type: Number
    Default: 5
    Description: "Read capacity units (only for PROVISIONED mode)."
    MinValue: 1 
    MaxValue: 1000
    ConstraintDescription: "The read capacity units must be between 1 and 1000."

  WriteCapacityUnits:
    Type: Number
    Default: 5
    Description: "Write capacity units (only for PROVISIONED mode)."
    MinValue: 1 
    MaxValue: 1000
    ConstraintDescription: "The write capacity units must be between 1 and 1000."

  PointInTimeRecoveryEnabled:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: "Whether point-in-time recovery is enabled."
    ConstraintDescription: "The value must be true or false."

  DynamoDBStreamType:
    Type: String
    Default: ""
    AllowedValues: ["", "KEYS_ONLY", "NEW_IMAGE", "OLD_IMAGE", "NEW_AND_OLD_IMAGES"]
    Description: "The type of DynamoDB stream to create."
    ConstraintDescription: "The value must be one of the allowed values."

  VpcEndpointId: 
    Type: String
    Default: ""
    Description: "ID of the VPC Endpoint for the Table."
    ConstraintDescription: "The VPC Endpoint ID must not be empty."
    AllowedPattern: "^$|^[a-zA-Z0-9-]+$"

Conditions:
  UseKmsMasterKey: !Not [!Equals [!Ref KmsMasterKeyAlias, ""]]
  HasSortKey: !Not [!Equals [!Ref SortKeyName, ""]]
  # HasLSI: !Not [!Equals [!Ref LocalSecondaryIndexes, ""]]
  # HasGSI: !Not [!Equals [!Ref GlobalSecondaryIndexes, ""]]
  HasTTLAttribute: !Not [!Equals [!Ref TTLAttributeName, ""]]
  # HasGSIWithSortKey: !Not [!Equals [!Select [3, !Split [",", !Ref GlobalSecondaryIndexes]], ""]]
  IsProvisioned: !Equals [!Ref BillingMode, "PROVISIONED"]
  IsPointInTimeRecoveryEnabled: !Equals [!Ref PointInTimeRecoveryEnabled, true]
  IsDynamoDBStreamEnabled: !Not [!Equals [!Ref DynamoDBStreamType, ""]]
  IsVpcEndpointEnabled: !Not [!Equals [!Ref VpcEndpointId, ""]]

Resources:
  ###################################### DynamoDB Table ############################################
  DynamoDBTable:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${TableBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      SSESpecification:
        !If
          - UseKmsMasterKey
          - SSEEnabled: true
            SSEType: KMS
            KMSMasterKeyId: !Sub "alias/${KmsMasterKeyAlias}"
          - !Ref AWS::NoValue
      AttributeDefinitions:
        - AttributeName: !Ref PartitionKeyName
          AttributeType: !Ref PartitionKeyType
        - !If 
          - HasSortKey
          - AttributeName: !Ref SortKeyName
            AttributeType: !Ref SortKeyType
          - !Ref AWS::NoValue
        # - !If
        #   - HasLSI
        #   - AttributeName: !Select [1, !Split [",", !Ref LocalSecondaryIndexes]]
        #     AttributeType: !Select [2, !Split [",", !Ref LocalSecondaryIndexes]]
        #   - !Ref AWS::NoValue
        # - !If
        #   - HasGSI
        #   - AttributeName: !Select [1, !Split [",", !Ref GlobalSecondaryIndexes]]
        #     AttributeType: !Select [2, !Split [",", !Ref GlobalSecondaryIndexes]]
        #   - !Ref AWS::NoValue
        - !If
          - HasTTLAttribute
          - AttributeName: !Ref TTLAttributeName
            AttributeType: N
          - !Ref AWS::NoValue
      KeySchema:
        - AttributeName: !Ref PartitionKeyName
          KeyType: HASH
        - !If 
          - HasSortKey
          - AttributeName: !Ref SortKeyName
            KeyType: RANGE
          - !Ref AWS::NoValue
      TableClass: !Ref TableClass
      StreamSpecification: 
        !If 
          - IsDynamoDBStreamEnabled
          - 
            StreamViewType: !Ref DynamoDBStreamType
          - !Ref AWS::NoValue
      TimeToLiveSpecification: !If 
        - HasTTLAttribute
        - 
          AttributeName: !Ref TTLAttributeName
          Enabled: true
        - !Ref AWS::NoValue
      BillingMode: !Ref BillingMode
      ProvisionedThroughput:
        !If 
          - IsProvisioned
          - ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
          - !Ref AWS::NoValue
      # LocalSecondaryIndexes:
      #   !If
      #     - HasLSI
      #     - - IndexName: !Select [0, !Split [",", !Ref LocalSecondaryIndexes]]
      #         KeySchema:
      #           - AttributeName: !Ref PartitionKeyName
      #             KeyType: HASH
      #           - AttributeName: !Select [1, !Split [",", !Ref LocalSecondaryIndexes]]
      #             KeyType: RANGE
      #         Projection:
      #           ProjectionType: ALL
      #     - !Ref AWS::NoValue
      # GlobalSecondaryIndexes:
      #   !If
      #     - HasGSI
      #     - - IndexName: !Select [0, !Split [",", !Ref GlobalSecondaryIndexes]]
      #         KeySchema:
      #           - AttributeName: !Select [1, !Split [",", !Ref GlobalSecondaryIndexes]]
      #             KeyType: HASH
      #           - !If
      #             - HasGSIWithSortKey
      #             - AttributeName: !Select [3, !Split [",", !Ref GlobalSecondaryIndexes]]
      #               KeyType: RANGE
      #             - !Ref AWS::NoValue
      #         Projection:
      #           ProjectionType: ALL
      #         ProvisionedThroughput:
      #           !If
      #             - IsProvisioned
      #             - ReadCapacityUnits: !Ref ReadCapacityUnits
      #               WriteCapacityUnits: !Ref WriteCapacityUnits
      #             - !Ref AWS::NoValue
      #     - !Ref AWS::NoValue
      PointInTimeRecoverySpecification:
        !If 
          - IsPointInTimeRecoveryEnabled
          - 
            PointInTimeRecoveryEnabled: true
          - !Ref AWS::NoValue
      ResourcePolicy: 
        !If 
          - IsVpcEndpointEnabled
          - 
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Deny
                  Principal: "*"
                  Action: 
                  - "dynamodb:*"
                  Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-${TableBaseName}-${Environment}-${AWS::Region}${CiBuild}"
                  Condition:
                    StringNotEquals:
                      "aws:sourceVpce": !Ref VpcEndpointId
            PolicyName: "DDBPolicy"
          - !Ref AWS::NoValue
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: CiBuild
          Value: !Ref CiBuild
Outputs:
  TableName:
    Value: !Ref DynamoDBTable
    Description: "The name of the created DynamoDB Table."
  TableArn:
    Value: !GetAtt DynamoDBTable.Arn
    Description: "The ARN of the created DynamoDB Table."
  DynamoDBStreamArn:
    Condition: IsDynamoDBStreamEnabled
    Value: !GetAtt DynamoDBTable.StreamArn
    Description: "The ARN of the DynamoDB Stream for the DDB Table."
